#!/bin/bash

if [ "$1" == "start" ]; then
	/etc/init.d/apache2 start
	/etc/init.d/mysql start
elif [ "$1" == "stop" ]; then
	/etc/init.d/apache2 stop
	/etc/init.d/mysql stop
elif [ "$1" == "restart" ]; then
    /etc/init.d/apache2 restart
    /etc/init.d/mysql restart
else
	echo "set parameter start|stop|restart"
	exit
fi